### ISSUE TITLE
Example on snack expo

### ISSUE THREAD

**Issue by Angelk90** [margelo/react-native-graph#5]
Hi @mrousavy , It would be possible to have the example above: https://snack.expo.dev

**Comment by papidb** [comment]
Expo isn't supported, so I don't think this is feasible now.

**Comment by flexbox** [comment]
Hey @Angelk90 
I have a feeling it will not land soon, because this library has a dependency to `react-native-skia`
https://github.com/Shopify/react-native-skia/issues/88#issuecomment-1108567957

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by mrousavy** [comment]
Hey - my library is purely JS (TypeScript) and no native code - so it would work on Expo Snack if all the dependencies worked on Expo Snack (Reanimated, RNGH and Skia). Unfortunately Skia does not work on Expo Snack (yet), so that's why I cannot create a snack. Closing this for now until the issue @flexbox linked is resolved.
